export const SUPPORTED_LOCALES: readonly ['en', 'fr'];
export type Locale = (typeof SUPPORTED_LOCALES)[number];
export const DEFAULT_LOCALE: Locale;
export const CV_PDF_FILENAME_PREFIX: string;
export const API_GLOBAL_PREFIX: string;
export type CvThemeColor = `#${string}`;
export const DEFAULT_THEME_COLOR: CvThemeColor;
export type CvThemePalette = {
  themeColor: CvThemeColor;
  sidebarBg: string;
  sidebarText: string;
  sidebarTitle: string;
  sidebarKicker: string;
  sidebarDivider: string;
  tagBg: string;
  tagBorder: string;
  tagText: string;
  accent: string;
  mutedText: string;
  cardBg: string;
  cardBgStrong: string;
  cardBorder: string;
  pageBg: string;
};
export function resolveCvTheme(themeColor?: string): CvThemePalette;
export function isSupportedLocale(value: string): value is Locale;
